### ISSUE TITLE
Settings button bricks HUD Manager

### ISSUE THREAD

**Issue by Chezpuf** [lexogrine/obserview#1]
Clicking the settings cog in the hud list causes HUD Manager to show a white screen, only remedy is relaunching Manager.

**Comment by osztenkurden** [comment]
Hello! This is an issue with Lexogrine HUD Manager. This will be fixed in 1.11.2. The issue is that there is no settings for this HUD, and button was incorrectly showing up anyway. I'll close this, as update will be released today.

EDIT: 1.11.2 is now published
